testしてみたよ

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -95,3 +95,40 @@ jobs:
         run: |
           chmod u+x .github/scripts/test01.sh
           .github/scripts/test01.sh "./product.php"
+
+      # 変更されたファイルに対して PHP_CodeSniffer を実行
+      - name: Run PHP CodeSniffer on specific lines
+        if: env.changed_files != ''
+        run: |
+          # 変更ファイルおよび行を変数に入れる
+          changed_files="${{ env.changed_files }}"
+
+          # エラーフラグ
+          # failed=false
+
+          # 変更行ごとにループ
+          for line in $changed_files; do
+            # ファイル名と行番号を分割
+            file=$(echo "$line" | cut -d':' -f1)
+            line_num=$(echo "$line" | cut -d':' -f2)
+            echo "Processing file: $file (line: $line_num)"
+
+            # 対象の行番号にエラーがあるか確認
+            #if grep -q "^[ ]\{1,2\}$line_num |" phpcs_result.txt; then
+            #  echo "Error detected on line $line_num in file $file"
+            #  echo "$file:$line_num" >> a.txt
+            #  grep "^[ ]\{1,2\}$line_num |" phpcs_result.txt >> a.txt
+            #  failed=true
+            #fi
+          done
+
+          # エラーが発生していた場合、ジョブを失敗として終了
+          #if [ "$failed" = true ]; then
+          #  echo "PHP CodeSniffer found issues on modified lines."
+          #  cat phpcs_result.txt
+          #  cat a.txt
+            # ワークフローをエラーとして終了
+          #  exit 1
+          #else
+          #  echo "No issues found in modified lines."
+          #fi
